#!/usr/bin/env python3
"""Build src/ofac-data.js from the official OFAC SDN list (stdlib only).

Extracts every "Digital Currency Address - <LABEL>" entry whose value is an EVM address (0x + 40 hex), with the SDN
entity name, programs and uid. Source: OFAC Sanctions List Service, SDN.XML (the same file that
https://www.treasury.gov/ofac/downloads/sdn.xml redirects to).

Usage: gen_ofac.py [--file SDN.XML] [--out src/ofac-data.js] [--min-count 50]
Refuses to write when fewer than --min-count EVM addresses are found, so a format change can't publish an empty list.
"""
import argparse
import datetime as dt
import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET

SOURCE_URL = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/SDN.XML"
PREFIX = "Digital Currency Address - "
EVM = re.compile(r"^0x[0-9a-fA-F]{40}$")


def local(tag):
    return tag.rsplit("}", 1)[-1]


def child_text(el, name):
    for c in el:
        if local(c.tag) == name:
            return (c.text or "").strip()
    return ""


def parse(stream):
    """Return (publish_date_iso, record_count, {lower_address: [[name, label, uid, [programs]], ...]})."""
    published, record_count, out = None, None, {}
    for _, el in ET.iterparse(stream, events=("end",)):
        tag = local(el.tag)
        if tag == "publshInformation":
            raw = child_text(el, "Publish_Date")
            if raw:
                published = dt.datetime.strptime(raw, "%m/%d/%Y").date().isoformat()
            rc = child_text(el, "Record_Count")
            record_count = int(rc) if rc.isdigit() else None
        elif tag == "sdnEntry":
            uid = child_text(el, "uid")
            last, first = child_text(el, "lastName"), child_text(el, "firstName")
            name = f"{first} {last}".strip() if first else last
            programs = sorted({(p.text or "").strip() for p in el.iter() if local(p.tag) == "program" and (p.text or "").strip()})
            for idel in el.iter():
                if local(idel.tag) != "id":
                    continue
                id_type, number = child_text(idel, "idType"), child_text(idel, "idNumber")
                if not id_type.startswith(PREFIX) or not EVM.match(number):
                    continue
                label = id_type[len(PREFIX):].strip()
                entry = [name, label, int(uid) if uid.isdigit() else uid, programs]
                bucket = out.setdefault(number.lower(), [])
                if entry not in bucket:
                    bucket.append(entry)
            el.clear()
    for v in out.values():
        v.sort(key=lambda e: (e[0], e[1]))
    return published, record_count, out


def render(source, published, record_count, data, generated_at):
    meta = {
        "source": source,
        "published": published,
        "sdn_record_count": record_count,
        "evm_address_count": len(data),
        "entity_count": len({e[2] for v in data.values() for e in v}),
    }
    lines = [
        "// Generated by tools/gen_ofac.py from the official OFAC SDN list. Do not edit by hand.",
        "// Each address maps to [[entity name, currency label, SDN uid, [programs]], ...].",
        f"export const OFAC_META = {json.dumps(meta, sort_keys=True)};",
        f"export const OFAC_GENERATED_AT = {json.dumps(generated_at)};",
        "export const OFAC = {",
    ]
    for addr in sorted(data):
        lines.append(f"  {json.dumps(addr)}: {json.dumps(data[addr], ensure_ascii=False)},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", help="parse a local SDN.XML instead of downloading")
    ap.add_argument("--out", default="src/ofac-data.js")
    ap.add_argument("--min-count", type=int, default=50)
    a = ap.parse_args()
    if a.file:
        source = SOURCE_URL
        with open(a.file, "rb") as f:
            published, record_count, data = parse(f)
    else:
        source = SOURCE_URL
        req = urllib.request.Request(SOURCE_URL, headers={"User-Agent": "joi-presign-ofac/1.0 (contact joi-ai@agentmail.to)"})
        with urllib.request.urlopen(req, timeout=180) as r:
            published, record_count, data = parse(r)
    if not published:
        sys.exit("REFUSED: no Publish_Date found; the format may have changed")
    if len(data) < a.min_count:
        sys.exit(f"REFUSED: only {len(data)} EVM addresses found (min {a.min_count}); the format may have changed")
    generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(render(source, published, record_count, data, generated_at))
    print(f"wrote {a.out}: {len(data)} EVM addresses, published {published}, SDN records {record_count}")


if __name__ == "__main__":
    main()
